name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-linux
            os: ubuntu-latest
            archive: tar.gz
          - target: aarch64-linux
            os: ubuntu-latest
            archive: tar.gz
          - target: x86_64-macos
            os: ubuntu-latest
            archive: tar.gz
          - target: aarch64-macos
            os: ubuntu-latest
            archive: tar.gz

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: build ${{ matrix.target }}
        run: zig build --release=fast -Dtarget=${{ matrix.target }} -Dlto=false

      - name: package
        run: |
          cd zig-out/bin
          tar czf ../../${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.target }}.${{ matrix.archive }} *

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.target }}.${{ matrix.archive }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
